### ISSUE TITLE
minidcos mac osx 10.11.6 fails to find certs

### ISSUE THREAD

**Issue by jbrinnand** [dcos/dcos-e2e#1579]
**Background - new installation of minidcos**
- mac OSX - El Capitan 10.11.6
- minidcos, version 2019.01.05.0
- docker-machine version 0.14.0, build 89b8332
- Docker version 17.06.0-ce, build 02c1d87

**docker create ./dcos_generate_config.sh --agents 0**
```
Traceback (most recent call last):
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/docker/api/client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://192.168.99.100:2376/v1.39/containers/create?name=dcos-e2e-default-3cd52-master-0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/minidcos", line 11, in <module>
    load_entry_point('DCOS-E2E==2019.1.5.0', 'console_scripts', 'minidcos')()
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/dcos_e2e_cli/dcos_docker/commands/create.py", line 491, in create
    doctor_command=doctor,
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/dcos_e2e_cli/common/create.py", line 40, in create_cluster
    public_agents=public_agents,
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/dcos_e2e/cluster.py", line 94, in __init__
    cluster_backend=cluster_backend,
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/dcos_e2e/backends/_docker/__init__.py", line 423, in __init__
    ports=ports,
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/dcos_e2e/backends/_docker/_containers.py", line 136, in start_dcos_container
    ports=ports or {},
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/docker/models/containers.py", line 824, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/docker/api/container.py", line 411, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/docker/api/container.py", line 422, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/docker/api/client.py", line 235, in _result
    self._raise_for_status(response)
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /private/var/folders/q8/1kk3b0nj7vg8hpsdvvtcy5740000gn/T/7c95a8b47249477abb79cc7130b3d5e8/f9626a452fce492f80ac10ee171c5a93/dcos-e2e-default-3cd52/include/certs")
```
The instructions have been followed to the letter but minidcos fails out of the box on my machine? I am sure something is missing, but I am not sure it might be: I have regenerated the certs on docker-machine. Uninstalled and re-installed minidcos and it failed the minidcos docker doctor checks. And it fails to generate the configuration.

**Comment by adamtheturtle** [comment]
I think that this may be because of a difference in how Docker for Mac works (that has been tested) and how docker-machine works. Is there any chance you could try using Docker for Mac?

**Comment by adamtheturtle** [comment]
https://github.com/dcos/dcos-e2e/issues/1579

To resolve this I have added a `minidcos docker doctor` check which fails nicely in this case.

There is currently no plan to support `docker-machine`.
If this is a blocker for you, please open another issue which explains why.

**Comment by jbrinnand** [comment]
I moved to using docker for mac some months ago. Things are working as
expected now. Thank you for following up. I really appreciate it.

Best,

John
