### ISSUE TITLE
“VBoxManage: error: Failed to create the VirtualBox object Code NS_ERROR_FACTORY_NOT_REGISTERED (0x80040154)” error while creating local dcos environment using vagrant in Ubuntu Linux 17.04 and 18.04

### ISSUE THREAD

**Issue by rajcspsg** [dcos/dcos-e2e#1594]
I'm trying to follow the steps [here](https://minidcos.readthedocs.io/en/latest/dcos-vagrant-cli.html) to install minidcos locally using vagrant.

I've installed minidcos using the below command here -

```
$ curl --fail -L https://github.com/dcos/dcos-e2e/releases/download/2018.12.10.0/minidcos -o /usr/local/bin/minidcos && \
  chmod +x /usr/local/bin/minidcos
minidcos vagrant doctor command output is
```

```
$ minidcos vagrant doctor
5/5 checks complete: ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████rajkumar@rajk$ minidcos vagrant create ./dcos_generate_config.sh --agents 0 
I assumed the above command is successfully snce there is no error in the output.


$ sudo minidcos vagrant create ./dcos_generate_config.sh --agents 0
VBoxManage: error: Failed to create the VirtualBox object!
VBoxManage: error: Code NS_ERROR_FACTORY_NOT_REGISTERED (0x80040154) - Class not registered (extended info not available)
VBoxManage: error: Most likely, the VirtualBox COM server is not running or failed to start.
Traceback (most recent call last):
  File "minidcos", line 4, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "site-packages/dcos_e2e_cli/dcos_vagrant/commands/create.py", line 136, in create
  File "site-packages/dcos_e2e_cli/dcos_vagrant/commands/_common.py", line 61, in existing_cluster_ids
  File "site-packages/dcos_e2e_cli/_vendor/vertigo_py/vertigo.py", line 45, in ls
  File "subprocess.py", line 336, in check_output
  File "subprocess.py", line 418, in run
subprocess.CalledProcessError: Command '['VBoxManage', 'list', 'vms']' returned non-zero exit status 1.
```

From the above error log I thought `VBoxManage list vms` command failed.
So I executed manually but it is working fine.

```
$ VBoxManage list vms
"Fedora28GNome" {386e23bc-9905-4dd9-ba35-100cf498cb5e}
"OpenSuseTumbleweed" {91f9de56-7a48-4dfe-9f3f-7cf6b764a0d1}
```

My minidcos version installed in my laptop is

```
$ minidcos --version
minidcos, version 2019.01.21.0
```
My ubuntu version is :

```
$ lsb_release  -a
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
```

I've asked the same question in [stackoverflow](https://stackoverflow.com/questions/53975416/vboxmanage-error-failed-to-create-the-virtualbox-object-error-while-creating) as well.

**Comment by rajcspsg** [comment]
minidcos works on mac OS sierra with both virtual box 5.1.x, 5.2.x and 6.0.x
minidcos work on ubuntu 16.04 and virtualbox 5.1.x and 5.2.x
minidcos doesn't work on ubuntu 17.xx/18.xx with virtualbox 5.2.x and 6.0.x
And it looks like similar issue happens in Arch Linux 
https://superuser.com/questions/1390130/virtualbox-error-ns-error-factory-not-registered-after-linux-4-20-and-vbox-6
So to me it seems like there is issue in latest linux kernel but I'm not sure.

**Comment by rajcspsg** [comment]
And I have tested this with latest minidcos Release 2019.04.18.2 on ubuntu 16.04 and virtualbox 6.0.4 and it is working fine. So definitely there is some changes in linux kernel that is causing this problem.

**Comment by rajcspsg** [comment]
I have created a bug in https://www.virtualbox.org/ticket/18446
