### ISSUE TITLE
Cannot change "oauth_enabled" to false

### ISSUE THREAD

**Issue by elenabdc** [dcos/dcos-e2e#1631]
I am trying to use minidcos without oauth login. I have found on dcos_generate_config.sh a line containing
```
'oauth_enabled': 'true',
```
If I change the value to false, I get the following error:
```
Try "minidcos docker doctor" for troubleshooting help.

Original error:
Extracting image from this script and loading into docker daemon, this step can take a few minutes
Error processing tar file(exit status 1): archive/tar: invalid tar header

Traceback (most recent call last):
  File "minidcos", line 4, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "site-packages/dcos_e2e_cli/dcos_docker/commands/create.py", line 451, in create
  File "site-packages/dcos_e2e_cli/common/utils.py", line 99, in get_variant
  File "site-packages/dcos_e2e_cli/_vendor/dcos_installer_tools/artifact_utils.py", line 109, in get_dcos_installer_details
  File "subprocess.py", line 395, in check_output
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['bash', '/root/minidcos/dcos_generate_config.sh', '--version']' returned non-zero exit status 1.
[32582] Failed to execute script minidcos
```

**Comment by timaa2k** [comment]
Hey,

You cannot change the line in the installer. Instead use the —extra-config parameter when creating a cluster and pass in a YAML file that overrides this config parameter.

In bash you can do —extra-config <(echo ”oauth_enabled: false”)
