### ISSUE TITLE
ModuleNotFoundError: No module named 'keyring.util.escape

### ISSUE THREAD

**Issue by Alwinius** [dcos/dcos-e2e#1643]
I installed minidcos with
`pip3 install --upgrade git+https://github.com/dcos/dcos-e2e.git@2019.04.02.1`
on a clean Ubuntu 18.04 in Virtualbox.
When I run `minidcos docker doctor` the output starts with 
```
Error initializing plugin EntryPoint('Windows (alt)', 'keyrings.alt.Windows', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/keyring/backend.py", line 190, in _load_plugins
    init_func = ep.load()
  File "/usr/local/lib/python3.6/dist-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('file', 'keyrings.alt.file', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/keyring/backend.py", line 190, in _load_plugins
    init_func = ep.load()
  File "/usr/local/lib/python3.6/dist-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/file.py", line 11, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('pyfs', 'keyrings.alt.pyfs', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/keyring/backend.py", line 190, in _load_plugins
    init_func = ep.load()
  File "/usr/local/lib/python3.6/dist-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
```
After that, the the checks appear to work normally.

**Comment by adamtheturtle** [comment]
I'm surprised to see `Windows` in the output given the Ubuntu host.

**Comment by RogerWeihrauch** [comment]
@all
Hello all. I am also facing this issue; concerning the last two error lines:
from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
I tried to install minidcos with pip3 AND pip; but did not find out which one may be the most comfortable one and also get this error when executing ' minidcos docker doctor'.
Also when creating a cluster i get some error messages; but donno where they come from:
(miniDCOS) ________________________________________________________________________________
| ~/miniDCOS @ 9StrEtcH9 (debian) 
| => minidcos docker create ./dcos_generate_config.sh --masters 3 --agents 11 --public-agents 3 --wait-for-dcos
Error initializing plugin EntryPoint('Gnome', 'keyrings.alt.Gnome', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/keyring/backend.py", line 190, in _load_plugins
    init_func = ep.load()
  File "/usr/local/lib/python3.5/dist-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Gnome.py", line 11, in <module>
    from keyring.py27compat import unicode_str
ImportError: cannot import name 'unicode_str'
Error initializing plugin EntryPoint('Windows (alt)', 'keyrings.alt.Windows', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/keyring/backend.py", line 190, in _load_plugins
    init_func = ep.load()
  File "/usr/local/lib/python3.5/dist-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 12, in <module>
    from keyring.util.escape import escape as escape_for_ini
ImportError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('file', 'keyrings.alt.file', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/keyring/backend.py", line 190, in _load_plugins
    init_func = ep.load()
  File "/usr/local/lib/python3.5/dist-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/file.py", line 12, in <module>
    from keyring.util.escape import escape as escape_for_ini
ImportError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('kwallet', 'keyrings.alt.kwallet', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/keyring/backend.py", line 190, in _load_plugins
    init_func = ep.load()
  File "/usr/local/lib/python3.5/dist-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/kwallet.py", line 6, in <module>
    from keyring.py27compat import unicode_str
ImportError: cannot import name 'unicode_str'
Error initializing plugin EntryPoint('pyfs', 'keyrings.alt.pyfs', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/keyring/backend.py", line 190, in _load_plugins
    init_func = ep.load()
  File "/usr/local/lib/python3.5/dist-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ImportError: No module named 'keyring.util.escape'
��� Determining DC/OS variant
��� Creating cluster
��� Installing DC/OS

HINT: I am in a virtualenv environment.
May be someone has a clue on this?

Regards,
Roger

**Comment by adamtheturtle** [comment]
This is frustrating.

`msrestazure` is a dependency of DC/OS Launch, which we vendor.
Let's take a look a the chain of events which lead to us installing a particular, old version of keychain which has this issue:

https://github.com/dcos/dcos-e2e/blob/feb3f8869597187da1d69b75294a58d8c29a44c3/indirect-requirements.txt#L4-L17

My ideal is to remove the dependency on DC/OS Launch and switch to Terraform, as per https://jira.mesosphere.com/browse/DCOS_OSS-4431.

**Comment by adamtheturtle** [comment]
I have reproduced this with:

```
$ docker run -it ubuntu bash
```

```
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

apt update -y && \
apt install -y software-properties-common && \
apt upgrade -y python-apt && \
add-apt-repository -y ppa:deadsnakes/ppa && \
apt update -y && \
apt upgrade -y gcc python3-dev python3.6-dev libffi-dev libssl-dev git python3-pip && \
pip3 install --upgrade git+https://github.com/dcos/dcos-e2e.git && \
```

The error shows here:

```
minidcos --help
```
