### ISSUE TITLE
Minidcos problem with a cluster that can't be delete

### ISSUE THREAD

**Issue by warnierdew** [dcos/dcos-e2e#1731]
When I use the command `minidcos docker destroy`, minidcos delete all node but the cluster is still, when I use `minidcos docker list` I get `default`.

And when I try to launch `minidcos docker clean -vvv` I get : 
`
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 380, in _make_request
  File "http/client.py", line 1321, in getresponse
  File "http/client.py", line 296, in begin
  File "http/client.py", line 257, in _read_status
  File "socket.py", line 589, in readinto
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 638, in urlopen
  File "site-packages/urllib3/util/retry.py", line 367, in increment
  File "site-packages/urllib3/packages/six.py", line 686, in reraise
  File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 386, in _make_request
  File "site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "minidcos", line 4, in <module>
  File "site-packages/click/core.py", line 764, in __call__
  File "site-packages/click/core.py", line 717, in main
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 1137, in invoke
  File "site-packages/click/core.py", line 956, in invoke
  File "site-packages/click/core.py", line 555, in invoke
  File "site-packages/dcos_e2e_cli/dcos_docker/commands/clean.py", line 45, in clean
  File "site-packages/docker/models/containers.py", line 424, in stop
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1149, in stop
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 226, in _post
  File "site-packages/requests/sessions.py", line 581, in post
  File "site-packages/requests/sessions.py", line 533, in request
  File "site-packages/requests/sessions.py", line 646, in send
  File "site-packages/requests/adapters.py", line 529, in send
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
[27984] Failed to execute script minidcos

`

**Comment by adamtheturtle** [comment]
Interesting - we saw this in https://jira.mesosphere.com/browse/DCOS_OSS-4313 and closed this with:

> Qian Zhang described that this may have been caused by his local /etc/hosts file. Let's close this and re-open if required.

Would you mind pasting your `/etc/hosts` file contents?

**Comment by warnierdew** [comment]
Finally, when I restart the server, the cluster just disappear, so now it's ok, thank you for your reply.
