### ISSUE TITLE
couldn't create vagrant flavor dcos cluster Error: "couldn't find login name -- expanding `~' (ArgumentError)"

### ISSUE THREAD

**Issue by rajcspsg** [dcos/dcos-e2e#1779]
I'm not able to create vagrant flavor dcos cluster. Please see below for details -

```

rajkumar@rajkumar: vagrant$sudo minidcos --version
minidcos, version 2019.05.24.0


rajkumar@rajkumar: vagrant$ sudo minidcos vagrant doctor7/7 checks complete: ███████████████████████████████████████████████████████████


rajkumar@rajkumar: vagrant$ sudo minidcos vagrant create ./dcos_generate_config.sh --agents 2
✔ Determining DC/OS variant
⠏ Creating cluster/opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/shared_helpers.rb:109:in `expand_path': couldn't find login name -- expanding `~' (ArgumentError)
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/shared_helpers.rb:109:in `expand_path'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/shared_helpers.rb:109:in `user_data_path'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/manager.rb:16:in `user_plugins_file'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/manager.rb:27:in `instance'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/kernel_v2/plugin.rb:43:in `<class:Plugin>'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/kernel_v2/plugin.rb:7:in `<module:Kernel_V2>'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/kernel_v2/plugin.rb:4:in `<module:VagrantPlugins>'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/kernel_v2/plugin.rb:3:in `<top (required)>'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant.rb:302:in `load'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant.rb:302:in `block in <top (required)>'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant.rb:316:in `block in <top (required)>'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant.rb:311:in `each'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant.rb:311:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:88:in `<main>'
Error creating cluster.
Full error:
  Command '['/usr/bin/vagrant', 'up']' returned non-zero exit status 1.
Try "minidcos vagrant doctor" for troubleshooting help.

rajkumar@rajkumar: vagrant$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

```

**Comment by adamtheturtle** [comment]
Interesting @rajcspsg - what happens if you do `cd ~`?
